# Form implementation generated from reading ui file 'UiExecuteSQL.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(264, 461)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.textEdit_sql_query = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_sql_query.setObjectName("textEdit_sql_query")
        self.mainLayout.addWidget(self.textEdit_sql_query)
        self.tableView_query_result = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_query_result.setObjectName("tableView_query_result")
        self.mainLayout.addWidget(self.tableView_query_result)
        self.btn_execute_query = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_execute_query.setObjectName("btn_execute_query")
        self.mainLayout.addWidget(self.btn_execute_query)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 264, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_sql_query.setPlaceholderText(_translate("MainWindow", "Введите SQL команду здесь"))
        self.btn_execute_query.setText(_translate("MainWindow", "Выполнить команду"))
