# Form implementation generated from reading ui file 'UiExecuteSQL.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExecuteSQL(object):
    def setupUi(self, ExecuteSQL):
        ExecuteSQL.setObjectName("ExecuteSQL")
        ExecuteSQL.resize(663, 433)
        self.centralwidget = QtWidgets.QWidget(parent=ExecuteSQL)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.textEdit_sql_query = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_sql_query.sizePolicy().hasHeightForWidth())
        self.textEdit_sql_query.setSizePolicy(sizePolicy)
        self.textEdit_sql_query.setObjectName("textEdit_sql_query")
        self.leftLayout.addWidget(self.textEdit_sql_query)
        self.logs_data_output_text = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logs_data_output_text.sizePolicy().hasHeightForWidth())
        self.logs_data_output_text.setSizePolicy(sizePolicy)
        self.logs_data_output_text.setObjectName("logs_data_output_text")
        self.leftLayout.addWidget(self.logs_data_output_text)
        self.btn_execute_query = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_execute_query.sizePolicy().hasHeightForWidth())
        self.btn_execute_query.setSizePolicy(sizePolicy)
        self.btn_execute_query.setObjectName("btn_execute_query")
        self.leftLayout.addWidget(self.btn_execute_query)
        self.mainLayout.addLayout(self.leftLayout)
        self.view_command_widget = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_command_widget.sizePolicy().hasHeightForWidth())
        self.view_command_widget.setSizePolicy(sizePolicy)
        self.view_command_widget.setObjectName("view_command_widget")
        self.view_command_widget.setColumnCount(0)
        self.view_command_widget.setRowCount(0)
        self.mainLayout.addWidget(self.view_command_widget)
        ExecuteSQL.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ExecuteSQL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        ExecuteSQL.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ExecuteSQL)
        self.statusbar.setObjectName("statusbar")
        ExecuteSQL.setStatusBar(self.statusbar)

        self.retranslateUi(ExecuteSQL)
        QtCore.QMetaObject.connectSlotsByName(ExecuteSQL)

    def retranslateUi(self, ExecuteSQL):
        _translate = QtCore.QCoreApplication.translate
        ExecuteSQL.setWindowTitle(_translate("ExecuteSQL", "Выполнить SQL"))
        self.textEdit_sql_query.setPlaceholderText(_translate("ExecuteSQL", "Введите SQL команду здесь"))
        self.btn_execute_query.setText(_translate("ExecuteSQL", "⌨️ Выполнить команду"))
